name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        compiler: ['msvc', 'mingw']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSVC
        if: matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup MinGW
        if: matrix.compiler == 'mingw'
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-toolchain
            make

      - name: Configure
        run: cmake -S . -B build -G "${{ matrix.compiler == 'msvc' && 'Visual Studio 17 2022' || 'MinGW Makefiles' }}"

      - name: Build
        run: cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-dlls
          path: |
            **/*.dll
